### ISSUE TITLE
IVML-Parser: Transparent handling of references does not work (as parameter for operations)

### ISSUE THREAD

**Issue by Elscha** [SSEHUB/EASyProducer#73]
Collections of references and collections of referenced types need different operations. E.g, the following won't work (for `strs2`):

```
project IVML {

    version v0;
    sequenceOf(String) strs1;
    sequenceOf(refTo(String)) strs2;

    setOf(String) set1 = toSet(strs1);
    setOf(String) set2 = toSet(strs2);

    def setOf(String) toSet(sequenceOf(String) stringArray) =
        stringArray.toSet();
}

```

This was used as workaround for #72 
CC: @eichelbe

**Comment by eichelbe** [comment]
So far not defined by the IVML language specification, or?

**Comment by eichelbe** [comment]
Right, due to the design of IVML and the specific typing of references and their related operations (see also (https://github.com/SSEHUB/EASyProducer/issues/72), there is no way for transparently handling references. Also in discussion with Jutta and Markus, transparent type query operations for reference and non-reference are not really needed.
